stages:
  - build
  - test
  - deploy

build_procedure:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker compose build

test_procedure:
  stage: test
  image: gradle:jdk17
  script:
    - ./gradlew test

deploy_procedure:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@$SSH_IP "
      cd /home/ubuntu/wastedisposalagencybe/ &&
      sudo git pull origin &&
      sudo docker compose down &&
      sudo docker compose up -d"