version: "3"

services:
  # container di RabbitMQ
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - wasteDisposalAgencyNetwork

  # container del backend dell'agenzia rifiuti
  wasteDisposalAgencyBE:
    image: openjdk:17-jdk-alpine
    container_name: wasteDisposalAgencyBE
    ports:
      - "80:8080"
      - "8001:8000"
    expose:
      - "8001"
    depends_on:
      - wasteDisposalAgencyDB
    networks:
      - wasteDisposalAgencyNetwork
    volumes:
      - ./build/libs/WasteDisposalAgencyBE-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  # container del database dell'agenzia rifiuti
  wasteDisposalAgencyDB:
    image: mongo:5.0
    container_name: wasteDisposalAgencyDB
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - wasteDisposalAgencyNetwork

# rete interna dell'agenzia rifiuti
networks:
  wasteDisposalAgencyNetwork:
    driver:
      "bridge"